### ISSUE TITLE
提交的信息没有地理位置

### ISSUE THREAD

**Issue by Haevil** [IanSmith123/ucas-covid19#26]
离京日期，去往何地，还有从何处返京都没有，是个人问题吗

**Comment by IanSmith123** [comment]
能否提供一份每日上报的填报表的截图，注意请将个人信息打码。目前我的填报表上没有这几项，不知道是不是不同人的表单不一样。

**Comment by Haevil** [comment]
https://i.loli.net/2021/01/21/sDpF7fbzYBCd6en.jpg

**Comment by IanSmith123** [comment]
感谢回复。
因为今日已经填报了，目前只能猜测原因，可能是 `是否离京` 选项选择了是的情况下会出现 `去往何处`选项，否则没有这个选项。
从何处返京可能情况类似。

此处应该需要修改提交的json的值，具体有哪些键需要重新分析，我可能需要周末才有时间修改。

如果你可以完成这个工作，欢迎PR :)

**Comment by IanSmith123** [comment]
https://github.com/IanSmith123/ucas-covid19/commit/d7c0a3a6dfaa31d6a9b003d86964f28882961ab0

已修复
