### ISSUE TITLE
好像不能用了？

### ISSUE THREAD

**Issue by EroData** [IanSmith123/ucas-covid19#27]
今早被班长叫起打卡，显示登陆失败？求更新拯救
![image](https://user-images.githubusercontent.com/26847296/105566865-5e4d3700-5d69-11eb-882c-254c58b9199e.png)
2021.1.23， "Error Fetching http headers" 不太明白是个什么问题。

我放在阿里云和Vultr上两个服务器都是这个问题。

**Comment by Cirn09** [comment]
是sep登录的接口崩了，你可以手动登录sep试试。

建议加个保存cookies的功能，sep的cookies有效期挺长的

**Comment by IanSmith123** [comment]
看起来是早晨的时候sep登陆的后端出问题了，我刚刚重新运行了一次，可以正常工作。
考虑增加一个打卡失败重试的机制。
另外，保存cookie的功能在自己服务器上部署的场景下是可以的，但是在github actions运行的情况下我暂时没有找到合适的缓存cookie的方式。

保存cookie这个功能有存在的必要，我稍后添加此逻辑。

todo: 添加保存cookie的功能，添加离京日期的处理逻辑，打卡失败重试。

**Comment by Cirn09** [comment]
另外建议把判断github actions环境然后读环境变量的逻辑改成无条件读环境变量，类似这样
```python
user = 'USER'
user_env = os.getenv('SEP_USER_NAME')
user = user_env if user_env else user
```
或者这样
```python
user = os.environ['SEP_USER_NAME'] if 'SEP_USER_NAME' in os.environ else 'USER'
```

github action的cookies可以手动添加进环境变量，自己服务器就保存文件就可以了。

最后建议打卡失败也发送一下通知。

**Comment by IanSmith123** [comment]
保存cookies的工作在 c26f42c1ed30238ef50f96ce7204d63d2b4b36f4 实现了，并且在 dcd3b6f979ecfb9f0a3e5aada0902e21653b68a4 实现了在github actions 缓存 cookies 的功能 。
打卡失败发送通知的工作在 a6abb1ff48889d2f285f98eb4fd1e2b489aeb2be 完成了。

我稍后将关闭此 issue。

**Comment by IanSmith123** [comment]
因为考虑到方便用户使用此脚本时修改几个变量， 检测github actions 运行获取环境变量和前面定义 user passwd等部分的代码未作修改。

**Comment by Cirn09** [comment]
> 因为考虑到方便用户使用此脚本时修改几个变量， 检测github actions 运行获取环境变量和前面定义 user passwd等部分的代码未作修改。

这样考虑的话，推荐写成这样

```python
user = 'USER'
...
user_env = os.getenv('SEP_USER_NAME')
user = user_env if user_env else user
```

~和上边好像没区别~

或者移动到单独的config.py中

```python
import config
...
user = user_env if user_env else config.user
```

这样也免去了每次commit都要把用户配置信息改回来的麻烦

**Comment by IanSmith123** [comment]
考虑到方便部署，所以只保留了一个py文件，没有拆分成多个文件，没有引入配置文件。

 debug 的时候确实每次要来回修改前面的配置文件， commit 之前要恢复修改，这点不是很方便，不过 debug的次数不是很多，这点还可以接受。
