### ISSUE TITLE
Github Actions定时打卡问题

### ISSUE THREAD

**Issue by zytlion** [IanSmith123/ucas-covid19#33]
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '10 0 * * *'
这个应该是要么push一下触发actions，要么8:10触发actions，但是8：10都不会触发，是有延迟吗？还是怎么回事？

**Comment by IanSmith123** [comment]
一般情况下是这样的。未执行的原因可能有几个：
1. 未开启 actions
> fork的仓库默认禁用了workflow，需要手动打开：点击 actions选项卡，点击I understand my workflows, go ahead and run them。
2. github 账户 actions 配额消耗完了
3. github 故障

**Comment by zytlion** [comment]
好像就是延迟
那我想问一下actions的配额是每天有限制吗？还是总共有限制次数的？

**Comment by IanSmith123** [comment]
https://github.com/settings/billing

**Comment by IanSmith123** [comment]
问题是否已解决？ @zytlion
