### ISSUE TITLE
接触时间问题

### ISSUE THREAD

**Issue by Allen-1231** [IanSmith123/ucas-covid19#36]
今日是否接触疑似/确诊人群虽然是填写的否，但是依然会有接触时间为19700101的问题吗，班长已经找过好几次了，请问该如何解决这个问题

**Comment by IanSmith123** [comment]
网站提交的数据包比以前少了一些字段，为了兼容适应可能的更改，因此项目里面仍然保留了这些字段。
最初以为不会有影响，现在看来是理解有误了  :(
稍后将修复此 issue 。

**Comment by IanSmith123** [comment]
问题应该已经修复，请 merge 最新代码。

**Comment by Allen-1231** [comment]
感谢感谢感谢！效率太高了！
