### ISSUE TITLE
貌似也可以在Windows本地设置一个定时任务？

### ISSUE THREAD

**Issue by spwpun** [IanSmith123/ucas-covid19#4]
菜鸡看不懂action的操作也没有服务器，哭泣。
写一个bat（python3 sub.py），然后用Windows的任务计划程序设置一个定时任务应该可以吧？

**Comment by IanSmith123** [comment]
可以的，但是需要保证电脑在打卡的时间内保持开机状态.
不过actions的操作哪里看不懂？可以详细说说么，可以一起完善一下文档。

**Comment by IanSmith123** [comment]
[https://github.com/spwpun/ucas-covid19/runs/1152581308?check_suite_focus=true](https://github.com/spwpun/ucas-covid19/runs/1152581308?check_suite_focus=true)
看起来你已经设置成功了 :)

**Comment by spwpun** [comment]
> https://github.com/spwpun/ucas-covid19/runs/1152581308?check_suite_focus=true
> 看起来你已经设置成功了 :)

我以为要自己新建一个workflow，hhh

**Comment by IanSmith123** [comment]
[https://github.com/IanSmith123/ucas-covid19#%E6%96%B9%E6%B3%95%E4%BA%8C-%E4%BD%BF%E7%94%A8-github-actions%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8](https://github.com/IanSmith123/ucas-covid19#%E6%96%B9%E6%B3%95%E4%BA%8C-%E4%BD%BF%E7%94%A8-github-actions%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8)
依次执行这里的步骤就可以了 :)
