### ISSUE TITLE
登陆失败，会话无效

### ISSUE THREAD

**Issue by rainylt** [IanSmith123/ucas-covid19#50]
```python
Traceback (most recent call last):
  File "./sub.py", line 294, in <module>
    report(username=user, ***
  File "./sub.py", line 290, in report
    submit(s, yesterday)
  File "./sub.py", line 123, in submit
    'realname': old['realname'],
TypeError: 'bool' object is not subscriptable
```
从十几天前开始报错了，不知道大家有没有这样的问题

**Comment by IanSmith123** [comment]
暂时无法复现，我这里目前还能正常工作。
![image](https://user-images.githubusercontent.com/19611084/143366222-c1b3ee2c-a1b7-4e08-84bf-50ce1c759e98.png)

你的仓库的 actions 在12天前仍然正常工作，但是12天前到今天没有执行 actions，而且任务号是连续的，暂时可以排除删除了执行记录的情况。
Github 可能因为某些原因没有执行定期的 actions（可能性很大），不建议过度依赖自动打卡，建议作为忘记人工打卡时的补救措施。

建议排错步骤：
1. 使用 sep 账号密码登录如下网址，观察能否进入到打卡的界面 
```
https://app.ucas.ac.cn/uc/wap/login?redirect=https%3A%2F%2Fapp.ucas.ac.cn%2Fsite%2FapplicationSquare%2Findex%3Fsid%3D2
```
2. 重新设定仓库内的账号密码等环境变量
3. 在自己的服务器上添加 crontab 任务，保证命令的定期执行 
4. 根据你自己仓库的 commit 记录，看起来你拥有超凡的 debug 能力，你可以试试自己 debug 下 :)

**Comment by ZanderZhao** [comment]
应该是两个情况
+ 两个月如果没有commit记录的话，github会停止此repo等action，所以至少两个月修改commit一次
+ 早上确实好几个同学打卡失败了，应该是8点左右那会学校服务器有问题，后面重新执行一下action或者手动打卡，明天如果不出意外的话，就没有意外

**Comment by rainylt** [comment]
> 你的仓库的 actions 在12天前仍然正常工作，但是12天前到今天没有执行 actions，而且任务号是连续的，暂时可以排除删除了执行记录的情况。 Github 可能因为某些原因没有执行定期的 actions（可能性很大），不建议过度依赖自动打卡，建议作为忘记人工打卡时的补救措施。

好的，多谢！

**Comment by rainylt** [comment]
> 应该是两个情况
> 
> * 两个月如果没有commit记录的话，github会停止此repo的action，所以至少两个月修改commit一次
> * 早上确实好几个同学打卡失败了，应该是8点左右那会学校服务器有问题，后面重新执行一下action或者手动打卡，明天如果不出意外的话，就没有意外

好的，多谢！

**Comment by IanSmith123** [comment]
> 早上确实好几个同学打卡失败了，应该是8点左右那会学校服务器有问题，后面重新执行一下action或者手动打卡，明天如果不出意外的话，就没有意外
@ZanderZhao 

早晨打卡失败的时候有收到程序发送的通知么？

**Comment by ZanderZhao** [comment]
> > 早上确实好几个同学打卡失败了，应该是8点左右那会学校服务器有问题，后面重新执行一下action或者手动打卡，明天如果不出意外的话，就没有意外
> > @ZanderZhao
> 
> 早晨打卡失败的时候有收到程序发送的通知么？

发了，会提示【登录失败】，不是脚本问题，应该是学校服务器问题或者那会即使加了偏移也有太多脚本运行在一起了？

**Comment by IanSmith123** [comment]
> > > 早上确实好几个同学打卡失败了，应该是8点左右那会学校服务器有问题，后面重新执行一下action或者手动打卡，明天如果不出意外的话，就没有意外
> > > @ZanderZhao
> > 
> > 
> > 早晨打卡失败的时候有收到程序发送的通知么？
> 
> 发了，会提示【登录失败】，不是脚本问题，应该是学校服务器问题或者那会即使加了偏移也有太多脚本运行在一起了？

感谢回复，只要不是没发送打卡失败的通知却异常退出就没有太大的问题。

看描述估计是学校服务器偶发故障，应该不用在意。
